from selenium.webdriver.common.by import By

first_brand_drop_down = (By.ID, 'p-6-0-2-brand')
first_model_drop_down = (By.ID, 'p-6-0-3-model')
first_generation_drop_down = (By.ID, 'p-6-0-4-generation')
year_from_button = (By.XPATH, '//div[@id="p-7-year"]//div//div[1]')
year_before_button = (By.XPATH, '//div[@id="p-7-year"]//div//div[2]')
bentley_button = (By.XPATH, '//li[@class="dropdown__listitem"][7]')
audi_button = (By.XPATH, '//li[@class="dropdown__listitem"][6]')
a3_button = (By.XPATH, '//ul[@class="dropdown-list dropdown-list--opened"]//li[@class="dropdown__listitem"][8]')
gen_8l_button = (By.XPATH, '//div[@class="dropdown__cards"]//div[@class="dropdown__card"][1]')
price_from_button = (By.XPATH, '//div[@class="price-compound"]//div[1]//label')
price_before_button = (By.XPATH, '//div[@class="price-compound"]//div[2]//label')
year_from_2022_button = (By.XPATH, '//ul[@class="dropdown-list dropdown-list--opened"]//li[3]')
year_before_2022_button = (By.XPATH, '//ul[@class="dropdown-list dropdown-list--opened"]//li[3]')
currency_button = (By.ID, 'p-10-price_currency')
byn_button = (By.XPATH, '//ul[@class="dropdown-list dropdown-list--opened"]//li[2]')

exclude_checkbox = (By.XPATH, '//label[@class="radiobutton"][2]')
show_button = (By.CSS_SELECTOR, '.button.button--secondary.button--block')
bentley_brand = (By.XPATH, '//button[@name="p-6-0-2-brand"]//span[2]')
bentley_brand_excl = (By.XPATH, '//button[@name="p-6-0-2-brand"]//span/span[2]/span')
year_2022_from = (By.XPATH, '//button[@title="2022"]//span[@class="dropdown-floatlabel__value"][1]')
year_2022_before = (By.XPATH, '//button[@title="2022"]//span[@class="dropdown-floatlabel__value"][1]')
listing__title = (By.CLASS_NAME, 'listing__title')
price_from_500 = (By.XPATH, '//div[@class="price-compound"]//div[1]//label')
price_before_5000 = (By.XPATH, '//div[@class="price-compound"]//div[2]//label')
a3_model = (By.XPATH, '//button[@name="p-6-0-3-model"]//span[2]')
a3_list = (By.XPATH, '//button[@data-item-label="A3"]')
list_8l = (By.XPATH, '//div[@class="dropdown__cards"]//div[@class="dropdown__card"][1]')
byn_currency = (By.XPATH, '//button[@class="dropdown__control dropdown__control--active dropdown-floatlabel"]//span[2]')

show_button_bentley = (By.XPATH, '//a[@href="https://cars.av.by/bentley"]')
show_button_audi = (By.XPATH, '//a[@href="https://cars.av.by/audi"]')
show_button_excl_bentley = (By.XPATH, '//a[@href="https://cars.av.by/filter?brands[0][exclude]=1&brands[0]['
                                      'brand]=1676"]')
show_button_audi_a3 = (By.XPATH, '//a[@href="https://cars.av.by/audi/a3"]')
show_button_audi_a3_8l = (By.XPATH, '//a[@href="https://cars.av.by/filter?brands[0][brand]=6&brands[0]['
                                    'model]=1428&brands[0][generation]=81"]')
show_button_from_2022 = (By.XPATH, '//a[@href="https://cars.av.by/filter?year[min]=2022"]')
show_button_before_2022 = (By.XPATH, '//a[@href="https://cars.av.by/filter?year[max]=2022"]')
show_button_from_price_500 = (By.XPATH, '//a[@href="https://cars.av.by/filter?price_usd[min]=500"]')
show_button_before_price_5000 = (By.XPATH, '//a[@href="https://cars.av.by/filter?price_usd[max]=5000"]')
show_button_5000_byn = (By.XPATH, '//a[@href="https://cars.av.by/filter?price_byn[max]=5000&price_currency=1"]')
show_button_byn = (By.XPATH, '//a[@href="https://cars.av.by/filter?price_currency=1"]')

